#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 13 14:43:39 2023

@author: dw16
"""

import torch
import matplotlib.pyplot as plt
import numpy as np

# Import data.
[PD]  = torch.load('PD.pt')
[T1]  = torch.load('T1.pt')
[T2]  = torch.load('T2.pt')
[T2p] = torch.load('T2p.pt')
[B0]  = torch.load('B0.pt')
[B1]  = torch.load('B1.pt')
[D]   = torch.load('D.pt')

plt.figure(1)
ax1 = plt.subplot(241)
plot1 = plt.imshow(np.rot90(PD))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
cbar = plt.colorbar(plot1,fraction=0.046,pad=0.04)
cbar.ax.tick_params(labelsize=18)
plt.set_cmap('inferno')
plt.clim(0,1)
tx = cbar.ax.yaxis.get_offset_text()
tx.set_fontsize(18)
ax1.set_xticklabels([])
ax1.set_yticklabels([])
ax1.set_xticks([])
ax1.set_yticks([])
plt.title('$PD$',fontsize=26)

ax2 = plt.subplot(242)
plot2 = plt.imshow(np.rot90(T1))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
cbar = plt.colorbar(plot2,fraction=0.046,pad=0.04)
cbar.ax.tick_params(labelsize=18)
plt.set_cmap('inferno')
plt.clim(0,4)
tx = cbar.ax.yaxis.get_offset_text()
tx.set_fontsize(18)
ax2.set_xticklabels([])
ax2.set_yticklabels([])
ax2.set_xticks([])
ax2.set_yticks([])
plt.title('$T_1$ [s]',fontsize=26)

ax3 = plt.subplot(243)
plot3 = plt.imshow(np.rot90(T2))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
cbar = plt.colorbar(plot3,fraction=0.046,pad=0.04)
cbar.ax.tick_params(labelsize=18)
plt.set_cmap('inferno')
plt.clim(0,1.7)
tx = cbar.ax.yaxis.get_offset_text()
tx.set_fontsize(14)
ax3.set_xticklabels([])
ax3.set_yticklabels([])
ax3.set_xticks([])
ax3.set_yticks([])
plt.title('$T_2$ [s]',fontsize=26)

ax4 = plt.subplot(244)
plot4 = plt.imshow(np.rot90(T2p/1000))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
cbar = plt.colorbar(plot4,fraction=0.046,pad=0.04)
cbar.ax.tick_params(labelsize=18)
plt.set_cmap('inferno')
plt.clim(0,0.35)
tx = cbar.ax.yaxis.get_offset_text()
tx.set_fontsize(14)
ax4.set_xticklabels([])
ax4.set_yticklabels([])
ax4.set_xticks([])
ax4.set_yticks([])
plt.title("$T_{2}$' [s]",fontsize=26)

ax5 = plt.subplot(245)
plot5 = plt.imshow(np.rot90(B0))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
cbar = plt.colorbar(plot5,fraction=0.046,pad=0.04)
cbar.ax.tick_params(labelsize=18)
plt.set_cmap('twilight')
plt.clim(-40,40)
tx = cbar.ax.yaxis.get_offset_text()
tx.set_fontsize(14)
ax5.set_xticklabels([])
ax5.set_yticklabels([])
ax5.set_xticks([])
ax5.set_yticks([])
plt.title('$B_0$ [Hz]',fontsize=26)

ax6 = plt.subplot(246)
plot6 = plt.imshow(np.rot90(B1))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
cbar = plt.colorbar(plot6,fraction=0.046,pad=0.04)
cbar.ax.tick_params(labelsize=18)
plt.set_cmap('viridis')
plt.clim(0.8,1.2)
tx = cbar.ax.yaxis.get_offset_text()
tx.set_fontsize(14)
ax6.set_xticklabels([])
ax6.set_yticklabels([])
ax6.set_xticks([])
ax6.set_yticks([])
plt.title('$B_1$ [rel]',fontsize=26)

ax7 = plt.subplot(247)
plot7 = plt.imshow(np.rot90(D))
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
cbar = plt.colorbar(plot7,fraction=0.046,pad=0.04)
cbar.ax.tick_params(labelsize=18)
plt.set_cmap('plasma')
plt.clim(0,3.2)
tx = cbar.ax.yaxis.get_offset_text()
tx.set_fontsize(14)
ax7.set_xticklabels([])
ax7.set_yticklabels([])
ax7.set_xticks([])
ax7.set_yticks([])
plt.title('$D$ [$10^{-3}mm^2/s$]',fontsize=26)

plt.subplots_adjust(top=1.1, bottom=-0.1, left=0.05, right=0.95,wspace=0.3,hspace=-0.4)